### ISSUE TITLE
Some npm packages will not be handled correctly containing several package.json files.

### ISSUE THREAD

**Issue by rdeangelis83** [CycloneDX/cyclonedx-webpack-plugin#1271]
## Describe the bug

It seems that some npm packages contains several package.json files. 
Together with the case that this additional package.json file doesn't contain a name property, the package will not be handled correctly and ignored.

Exampe npm module: luxon@3.3.0 

## To Reproduce

1. Create a simply project with a dependency to luxon@3.3.0
2. Add the cyclonedy plugin and perform a build

## Expected behavior

luxon@3.3.0 should appear in the generated bom file

## Screenshots or output-paste
In the screenshot the second package.json contained in luxon@3.3.0 under der src dir.
It doesn't contain a name so the cyclonedx-webpack-plugin will ignore the component.
![image](https://github.com/CycloneDX/cyclonedx-webpack-plugin/assets/1331961/f3940328-3376-488c-b5de-1ef8097ae2dd)

## Environment

- _@cyclonedx/webpack-plugin_ version: 3.9.2
- webpack version: 5.70.0
- Node version: 16
- OS: windows 10

## Additional context

In the getPackageDescription we could ignore such package.json files without name and continue to search for a valid package.json file.
https://github.com/CycloneDX/cyclonedx-webpack-plugin/blob/eb0ba22c5cb47c38db686b5e7d89dd10a63794e0/src/_helpers.ts#L28

**Comment by jkowalleck** [comment]
This is a known issue. It is not expected to be fixed, since this is just out of scope.

Please contact the author of such `package.json` and have them fix the file as expected.

see exactly the same "luxon" issue here:  https://github.com/CycloneDX/cyclonedx-webpack-plugin/issues/778#issuecomment-1494201468

**Comment by jkowalleck** [comment]
@rdeangelis83 you might help by providing a test-bed for the case.
Unfortunately @tomsontom [missed on that](https://github.com/CycloneDX/cyclonedx-webpack-plugin/issues/1237#issuecomment-1836590358), so the fix for the bug you described never went further.

**Comment by rdeangelis83** [comment]
Hi @jkowalleck,
Yes I can do that in the next few days.
But let me try to understand why ignoring such package json files and continue to traverse the path up is not a solution like you already mentioned in https://github.com/CycloneDX/cyclonedx-webpack-plugin/issues/778#issuecomment-1494201468. 

The npm specification says that the name and version are required fields: https://docs.npmjs.com/creating-a-package-json-file.

I would like to understand to what false positives and other problems that would lead.

Maybe we could find some other solution to solve that problems. For example stop to traverse up as soon we find a parent with the name node_modules. 

Or in case that the name is missing to extract the name from the path like you already suggested by traverse the path up and use the dir name that has node_modules as parent dir?

**Comment by jkowalleck** [comment]
> Maybe we could find some other solution to solve that problems. For example stop to traverse up as soon we find a parent with the name node_modules.

`node_modules` folder, for the reason oaf injected package-lookup, or for the reason that the package is in global package store. 

Traversing upwards is just no solution. Yes, package name is required by `npm` conventions, but not by nodejs rules. Therefore, the first found `package.json` is the one that is relevant for lookups and so on.

The only solution I see, in a case where no name is given, is to use the relative path as the dummy package name.
