### ISSUE TITLE
Support for webpack

### ISSUE THREAD

**Issue by sergioasantiago** [CycloneDX/cyclonedx-webpack-plugin#2]
Hey, I hope you are doing well!

I'm a fan and user of cyclonedx plugins, and I was wondering if I can integrate our projects that uses webpack to export the dependencies bom using this plugin.

Unfortunately I found out that there are not much progress on this, so I was just wondering if there is any intention to conver webpack plugins as well?

Sorry for the hassle and thanks for you nice work!

**Comment by coderpatros** [comment]
Hi @sergioasantiago 

From what I remember Steve had a first cut implementation working for this. But I know he has been busy so he might not have gotten it ready for release yet.

**Comment by stevespringett** [comment]
@sergioasantiago There's actually been a ton of progress on this. The Node module is being completely rewritten from the ground up, and it's nearly complete. It'll like be released this weekend.

v2.0 of the node module not only supports the generation of BOMs from npm, but it also provides the necessary object model and functions to programmatically parse packages and create JSON and XML BOMs.

The upcoming CycloneDX Authoring Tool (CAT) as well as the webpack plugin both use the new node module. 

I haven't checked in code for the webpack module yet, but will likely do so later this weekend. I've been using it and it's working flawlessly on the Dependency-Track frontend project. Its actually quite amazing to compare the BOM generated from npm vs the BOM generated from the webpack plugin. 

I could sure use some testing, feedback, and PRs when its available.

**Comment by stevespringett** [comment]
Update Proton Mail web client example SBOM when this ticket is complete.

**Comment by stevespringett** [comment]
Update: The initial checkin is complete. It's not quite ready - currently relies on an unreleased version of the CycloneDX Node module which I'll likely commit tomorrow. And a bit of work still needs to done on the dependency graph. All the component information however is in place. Likely just a few days away from initial release.

**Comment by stevespringett** [comment]
v1.0.0 is now available from npm.js
