### ISSUE TITLE
feat: normalize PackageJson-like data before use

### ISSUE THREAD

**Issue by jkowalleck** [CycloneDX/cyclonedx-webpack-plugin#678]
## Is your feature request related to a problem? Please describe.

caused by https://github.com/CycloneDX/cyclonedx-javascript-library/issues/517
it is encouraged to normalize PackageJson-like data before use.

## Describe the solution you'd like

use https://www.npmjs.com/package/normalize-package-data to normalize PackageJson-like structures,
before working with them.

## Describe alternatives you've considered

none

## Additional context

see https://github.com/CycloneDX/cyclonedx-javascript-library/issues/517

**Comment by jkowalleck** [comment]
@lal12 FYI

**Comment by jkowalleck** [comment]
@lal12 would you be so kind and check if v3.3.0 of this webpack plugin fixed your SBOM?

**Comment by lal12** [comment]
@jkowalleck it does :+1:
